// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _fft_HH_
#define _fft_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "bit_reverse.h"
#include "dut_faddfsub_32nsdEe.h"
#include "dut_fmul_32ns_32neOg.h"
#include "dut_fptrunc_64ns_fYi.h"
#include "fft_cosa_lookup_tbkb.h"
#include "fft_sina_lookup_tcud.h"

namespace ap_rtl {

struct fft : public sc_module {
    // Port declarations 16
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<14> > X_R_address0;
    sc_out< sc_logic > X_R_ce0;
    sc_out< sc_logic > X_R_we0;
    sc_out< sc_lv<32> > X_R_d0;
    sc_in< sc_lv<32> > X_R_q0;
    sc_out< sc_lv<14> > X_I_address0;
    sc_out< sc_logic > X_I_ce0;
    sc_out< sc_logic > X_I_we0;
    sc_out< sc_lv<32> > X_I_d0;
    sc_in< sc_lv<32> > X_I_q0;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    fft(sc_module_name name);
    SC_HAS_PROCESS(fft);

    ~fft();

    sc_trace_file* mVcdFile;

    fft_cosa_lookup_tbkb* cosa_lookup_table_U;
    fft_sina_lookup_tcud* sina_lookup_table_U;
    bit_reverse* grp_bit_reverse_fu_190;
    dut_faddfsub_32nsdEe<1,5,32,32,32>* dut_faddfsub_32nsdEe_U3;
    dut_faddfsub_32nsdEe<1,5,32,32,32>* dut_faddfsub_32nsdEe_U4;
    dut_fmul_32ns_32neOg<1,4,32,32,32>* dut_fmul_32ns_32neOg_U5;
    dut_fmul_32ns_32neOg<1,4,32,32,32>* dut_fmul_32ns_32neOg_U6;
    dut_fmul_32ns_32neOg<1,4,32,32,32>* dut_fmul_32ns_32neOg_U7;
    dut_fmul_32ns_32neOg<1,4,32,32,32>* dut_fmul_32ns_32neOg_U8;
    dut_fptrunc_64ns_fYi<1,2,64,32>* dut_fptrunc_64ns_fYi_U9;
    dut_fptrunc_64ns_fYi<1,2,64,32>* dut_fptrunc_64ns_fYi_U10;
    sc_signal< sc_lv<31> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<13> > cosa_lookup_table_address0;
    sc_signal< sc_logic > cosa_lookup_table_ce0;
    sc_signal< sc_lv<64> > cosa_lookup_table_q0;
    sc_signal< sc_lv<13> > sina_lookup_table_address0;
    sc_signal< sc_logic > sina_lookup_table_ce0;
    sc_signal< sc_lv<64> > sina_lookup_table_q0;
    sc_signal< sc_lv<32> > reg_230;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_logic > ap_CS_fsm_state17;
    sc_signal< sc_logic > ap_CS_fsm_state25;
    sc_signal< sc_lv<32> > reg_237;
    sc_signal< sc_lv<32> > grp_fu_198_p2;
    sc_signal< sc_lv<32> > reg_244;
    sc_signal< sc_logic > ap_CS_fsm_state30;
    sc_signal< sc_lv<32> > grp_fu_202_p2;
    sc_signal< sc_lv<32> > reg_250;
    sc_signal< sc_lv<32> > zext_ln1788_fu_272_p1;
    sc_signal< sc_lv<32> > zext_ln1788_reg_420;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<1> > icmp_ln1786_fu_260_p2;
    sc_signal< sc_lv<14> > trunc_ln_fu_276_p4;
    sc_signal< sc_lv<14> > trunc_ln_reg_425;
    sc_signal< sc_lv<32> > numBF_fu_286_p1;
    sc_signal< sc_lv<32> > numBF_reg_430;
    sc_signal< sc_lv<32> > i_cast_fu_290_p1;
    sc_signal< sc_lv<32> > i_cast_reg_435;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<14> > j_fu_299_p2;
    sc_signal< sc_lv<14> > j_reg_443;
    sc_signal< sc_lv<1> > icmp_ln1796_fu_294_p2;
    sc_signal< sc_lv<32> > step_fu_359_p3;
    sc_signal< sc_lv<4> > stage_fu_367_p2;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<32> > grp_fu_222_p1;
    sc_signal< sc_lv<32> > c_reg_478;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<32> > grp_fu_226_p1;
    sc_signal< sc_lv<32> > s_reg_484;
    sc_signal< sc_lv<14> > X_R_addr_reg_493;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<1> > icmp_ln1813_fu_383_p2;
    sc_signal< sc_lv<14> > X_I_addr_reg_498;
    sc_signal< sc_lv<14> > X_R_addr_1_reg_503;
    sc_signal< sc_lv<14> > X_I_addr_1_reg_508;
    sc_signal< sc_lv<32> > i_1_fu_406_p2;
    sc_signal< sc_lv<32> > i_1_reg_513;
    sc_signal< sc_lv<32> > k_fu_411_p2;
    sc_signal< sc_lv<32> > grp_fu_206_p2;
    sc_signal< sc_lv<32> > tmp_reg_523;
    sc_signal< sc_logic > ap_CS_fsm_state12;
    sc_signal< sc_lv<32> > grp_fu_210_p2;
    sc_signal< sc_lv<32> > tmp_1_reg_528;
    sc_signal< sc_lv<32> > grp_fu_214_p2;
    sc_signal< sc_lv<32> > tmp_2_reg_533;
    sc_signal< sc_lv<32> > grp_fu_218_p2;
    sc_signal< sc_lv<32> > tmp_3_reg_538;
    sc_signal< sc_lv<32> > tmp_4_reg_543;
    sc_signal< sc_logic > ap_CS_fsm_state22;
    sc_signal< sc_lv<32> > tmp_5_reg_548;
    sc_signal< sc_logic > grp_bit_reverse_fu_190_ap_start;
    sc_signal< sc_logic > grp_bit_reverse_fu_190_ap_done;
    sc_signal< sc_logic > grp_bit_reverse_fu_190_ap_idle;
    sc_signal< sc_logic > grp_bit_reverse_fu_190_ap_ready;
    sc_signal< sc_lv<14> > grp_bit_reverse_fu_190_X_R_address0;
    sc_signal< sc_logic > grp_bit_reverse_fu_190_X_R_ce0;
    sc_signal< sc_logic > grp_bit_reverse_fu_190_X_R_we0;
    sc_signal< sc_lv<32> > grp_bit_reverse_fu_190_X_R_d0;
    sc_signal< sc_lv<14> > grp_bit_reverse_fu_190_X_I_address0;
    sc_signal< sc_logic > grp_bit_reverse_fu_190_X_I_ce0;
    sc_signal< sc_logic > grp_bit_reverse_fu_190_X_I_we0;
    sc_signal< sc_lv<32> > grp_bit_reverse_fu_190_X_I_d0;
    sc_signal< sc_lv<32> > step_0_reg_134;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<4> > stage_0_reg_146;
    sc_signal< sc_lv<14> > i_reg_158;
    sc_signal< sc_lv<32> > k_0_reg_169;
    sc_signal< sc_lv<32> > i_0_reg_181;
    sc_signal< sc_logic > ap_CS_fsm_state31;
    sc_signal< sc_logic > grp_bit_reverse_fu_190_ap_start_reg;
    sc_signal< sc_lv<64> > sext_ln1797_fu_305_p1;
    sc_signal< sc_lv<64> > sext_ln1816_fu_394_p1;
    sc_signal< sc_lv<64> > sext_ln1818_fu_400_p1;
    sc_signal< sc_logic > ap_CS_fsm_state16;
    sc_signal< sc_logic > ap_CS_fsm_state23;
    sc_signal< sc_logic > ap_CS_fsm_state24;
    sc_signal< sc_lv<32> > grp_fu_198_p0;
    sc_signal< sc_lv<32> > grp_fu_198_p1;
    sc_signal< sc_logic > ap_CS_fsm_state13;
    sc_signal< sc_logic > ap_CS_fsm_state18;
    sc_signal< sc_logic > ap_CS_fsm_state26;
    sc_signal< sc_lv<32> > grp_fu_202_p0;
    sc_signal< sc_lv<32> > grp_fu_202_p1;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_lv<15> > zext_ln1786_fu_256_p1;
    sc_signal< sc_lv<15> > DFTpts_fu_266_p2;
    sc_signal< sc_lv<32> > sub_ln1825_fu_319_p2;
    sc_signal< sc_lv<31> > lshr_ln1825_1_fu_325_p4;
    sc_signal< sc_lv<32> > zext_ln1825_fu_335_p1;
    sc_signal< sc_lv<31> > lshr_ln1825_2_fu_345_p4;
    sc_signal< sc_lv<1> > tmp_10_fu_311_p3;
    sc_signal< sc_lv<32> > sub_ln1825_1_fu_339_p2;
    sc_signal< sc_lv<32> > zext_ln1825_1_fu_355_p1;
    sc_signal< sc_lv<18> > tmp_11_fu_373_p4;
    sc_signal< sc_lv<32> > i_lower_fu_389_p2;
    sc_signal< sc_lv<2> > grp_fu_198_opcode;
    sc_signal< sc_lv<2> > grp_fu_202_opcode;
    sc_signal< sc_lv<31> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<31> ap_ST_fsm_state1;
    static const sc_lv<31> ap_ST_fsm_state2;
    static const sc_lv<31> ap_ST_fsm_state3;
    static const sc_lv<31> ap_ST_fsm_state4;
    static const sc_lv<31> ap_ST_fsm_state5;
    static const sc_lv<31> ap_ST_fsm_state6;
    static const sc_lv<31> ap_ST_fsm_state7;
    static const sc_lv<31> ap_ST_fsm_state8;
    static const sc_lv<31> ap_ST_fsm_state9;
    static const sc_lv<31> ap_ST_fsm_state10;
    static const sc_lv<31> ap_ST_fsm_state11;
    static const sc_lv<31> ap_ST_fsm_state12;
    static const sc_lv<31> ap_ST_fsm_state13;
    static const sc_lv<31> ap_ST_fsm_state14;
    static const sc_lv<31> ap_ST_fsm_state15;
    static const sc_lv<31> ap_ST_fsm_state16;
    static const sc_lv<31> ap_ST_fsm_state17;
    static const sc_lv<31> ap_ST_fsm_state18;
    static const sc_lv<31> ap_ST_fsm_state19;
    static const sc_lv<31> ap_ST_fsm_state20;
    static const sc_lv<31> ap_ST_fsm_state21;
    static const sc_lv<31> ap_ST_fsm_state22;
    static const sc_lv<31> ap_ST_fsm_state23;
    static const sc_lv<31> ap_ST_fsm_state24;
    static const sc_lv<31> ap_ST_fsm_state25;
    static const sc_lv<31> ap_ST_fsm_state26;
    static const sc_lv<31> ap_ST_fsm_state27;
    static const sc_lv<31> ap_ST_fsm_state28;
    static const sc_lv<31> ap_ST_fsm_state29;
    static const sc_lv<31> ap_ST_fsm_state30;
    static const sc_lv<31> ap_ST_fsm_state31;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_18;
    static const sc_lv<32> ap_const_lv32_1D;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_15;
    static const sc_lv<32> ap_const_lv32_2000;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<14> ap_const_lv14_0;
    static const sc_lv<32> ap_const_lv32_1E;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<32> ap_const_lv32_16;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<32> ap_const_lv32_11;
    static const sc_lv<32> ap_const_lv32_19;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<4> ap_const_lv4_F;
    static const sc_lv<15> ap_const_lv15_1;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<14> ap_const_lv14_1;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<18> ap_const_lv18_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<2> ap_const_lv2_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_DFTpts_fu_266_p2();
    void thread_X_I_address0();
    void thread_X_I_ce0();
    void thread_X_I_d0();
    void thread_X_I_we0();
    void thread_X_R_address0();
    void thread_X_R_ce0();
    void thread_X_R_d0();
    void thread_X_R_we0();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state12();
    void thread_ap_CS_fsm_state13();
    void thread_ap_CS_fsm_state16();
    void thread_ap_CS_fsm_state17();
    void thread_ap_CS_fsm_state18();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state22();
    void thread_ap_CS_fsm_state23();
    void thread_ap_CS_fsm_state24();
    void thread_ap_CS_fsm_state25();
    void thread_ap_CS_fsm_state26();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state30();
    void thread_ap_CS_fsm_state31();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_cosa_lookup_table_address0();
    void thread_cosa_lookup_table_ce0();
    void thread_grp_bit_reverse_fu_190_ap_start();
    void thread_grp_fu_198_opcode();
    void thread_grp_fu_198_p0();
    void thread_grp_fu_198_p1();
    void thread_grp_fu_202_opcode();
    void thread_grp_fu_202_p0();
    void thread_grp_fu_202_p1();
    void thread_i_1_fu_406_p2();
    void thread_i_cast_fu_290_p1();
    void thread_i_lower_fu_389_p2();
    void thread_icmp_ln1786_fu_260_p2();
    void thread_icmp_ln1796_fu_294_p2();
    void thread_icmp_ln1813_fu_383_p2();
    void thread_j_fu_299_p2();
    void thread_k_fu_411_p2();
    void thread_lshr_ln1825_1_fu_325_p4();
    void thread_lshr_ln1825_2_fu_345_p4();
    void thread_numBF_fu_286_p1();
    void thread_sext_ln1797_fu_305_p1();
    void thread_sext_ln1816_fu_394_p1();
    void thread_sext_ln1818_fu_400_p1();
    void thread_sina_lookup_table_address0();
    void thread_sina_lookup_table_ce0();
    void thread_stage_fu_367_p2();
    void thread_step_fu_359_p3();
    void thread_sub_ln1825_1_fu_339_p2();
    void thread_sub_ln1825_fu_319_p2();
    void thread_tmp_10_fu_311_p3();
    void thread_tmp_11_fu_373_p4();
    void thread_trunc_ln_fu_276_p4();
    void thread_zext_ln1786_fu_256_p1();
    void thread_zext_ln1788_fu_272_p1();
    void thread_zext_ln1825_1_fu_355_p1();
    void thread_zext_ln1825_fu_335_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
